from config import settings
from db.base_class import Base
from geoalchemy2 import Geometry
from sqlalchemy import Column, ForeignKey, Index, Integer, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.declarative import declared_attr
from sqlalchemy_json import mutable_json_type


class Egib(Base):
    __tablename__ = "egib"
    id = Column(Integer, primary_key=True)
    import_id = Column(Integer, ForeignKey("import_metadata.id", ondelete="CASCADE"))
    identyfikator = Column(String)
    kst = Column(String)
    # kst_norm = Column(String)
    other = Column(mutable_json_type(dbtype=JSONB, nested=True))  # type: ignore
    # Alembic doesn't know about the autogenerated spatial_index.
    # Set it false here and create it in __table_args__ :(
    geom = Column(Geometry("Multipolygon", spatial_index=False, srid=settings.DB_SRID))  # type: ignore # noqa

    @declared_attr
    def __table_args__(cls):
        return (
            Index(
                "idx_{}_geom".format(cls.__tablename__),
                "geom",
                postgresql_using="gist",
            ),
        )
