"""add address points table

Revision ID: 19bdecfcd5c0
Revises: 6b9c32255ded
Create Date: 2022-02-08 18:31:26.470369

"""
import geoalchemy2 as ga2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19bdecfcd5c0"
down_revision = "6b9c32255ded"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address_point",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("miejscowosc", sa.String(), nullable=True),
        sa.Column("kod_pocztowy", sa.String(length=6), nullable=True),
        sa.Column("ulica", sa.String(), nullable=True),
        sa.Column("numer_porzadkowy", sa.String(), nullable=True),
        sa.Column(
            "geom",
            ga2.types.Geometry(
                geometry_type="POINT",
                srid=2180,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("other", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["import_metadata.id"],
            name=op.f("fk_address_point_import_id_import_metadata"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address_point")),
    )
    op.create_index(
        "idx_address_point_geom",
        "address_point",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_address_point_geom", table_name="address_point", postgresql_using="gist"
    )
    op.drop_table("address_point")
    # ### end Alembic commands ###
