"""Add teryt

Revision ID: 71ed79e063bc
Revises: a29a01a06c72
Create Date: 2022-01-03 15:20:04.682263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ed79e063bc'
down_revision = 'a29a01a06c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terc',
    sa.Column('kod', sa.String(length=7), nullable=False),
    sa.Column('woj', sa.String(length=2), nullable=True),
    sa.Column('pow', sa.String(length=2), nullable=True),
    sa.Column('gmi', sa.String(length=2), nullable=True),
    sa.Column('rodz', sa.String(length=1), nullable=True),
    sa.Column('nazwa', sa.String(), nullable=True),
    sa.Column('nazwa_dod', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('kod')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terc')
    # ### end Alembic commands ###
